package com.turlygazhy.entity;

/**
 * Created by user on 1/17/17.
 */
public enum WaitingType {
    NISHA, CONTACT, PLAN_NAME, PLAN_GOAL, READED_COUNT, GROUP_ID, GOAL_NAME, GOAL_DIGIT, AVAILABLE_TIME_START, AVAILABLE_TIME_END, CHANGE_GOAL, GOAL_COMPLETED, BOOK_NAME, CHECK_BOOK_NAME, NEW_THESIS, CHANGE_THESIS, CHANGE_PAGE, PERIOD, PERIOD_START, PERIOD_END, CHOOSE_GOAL, CHANGE_TYPE, GOAL_NEW_NAME, BOT_NAME, BOT_TOKEN, BOT_ID, BOT_CHANGE_ACTION, NEW_BUTTON_NAME, COMMAND_TYPE, MESSAGE_FOR_BUTTON, PHOTO_FOR_BUTTON, IS_NEW_ROW, TEXT, PHOTO, INLINE_LINK, LINK_NAME, INFO_NAME, INFO_TYPE, NEED_OPTIONS, OPTION, CATEGORY, SCRIPT, CONFIRM, NAVIKI
}
